### ISSUE TITLE
compileSdkVersion 26 Problem

### ISSUE THREAD

**Issue by GolfettoGuilherme** [BCGDV-ASIA/android-widget-fanmenu#9]
I've been using this lib in compileSdkVersion 22 without any problems, but, recent problems made me to upgrade compileSdkVersion to 26 and the app crashes for now on, here is the stacktrace

` java.lang.IllegalArgumentException: width and height must be > 0
                      at android.graphics.Bitmap.createBitmap(Bitmap.java:1013)
                      at android.graphics.Bitmap.createBitmap(Bitmap.java:980)
                      at android.graphics.Bitmap.createBitmap(Bitmap.java:930)
                      at android.graphics.Bitmap.createBitmap(Bitmap.java:891)
                      at com.bcgdv.asia.lib.fanmenu.FanMenuButtons.initIfNeeded(FanMenuButtons.java:243)
                      at com.bcgdv.asia.lib.fanmenu.FanMenuButtons.animateIn(FanMenuButtons.java:372)
                      at com.bcgdv.asia.lib.fanmenu.FanMenuButtons.toggleShow(FanMenuButtons.java:357)
                      at br.com.domain.domain.MainActivity$3.onClick(MainActivity.java:189)
                      at android.view.View.performClick(View.java:6256)
                      at android.view.View$PerformClick.run(View.java:24711)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:169)
                      at android.app.ActivityThread.main(ActivityThread.java:6595)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by alphamu** [comment]
Please try version 1.4. which I just pushed out.
I haven't change the code any in regards to the issue you reported, but my sample app seems to be running on compileSdk 26 without issues. Let me know if the problem persists.
